version: '3.0'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.16
    env_file:
      - docker/docker.env
    volumes:
      - ./docker/:/docker-entrypoint-initdb.d/
#      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
